test: remove test for priority fee that's ‘too high’
solana-labs/solana-web3.js pull request #1238
Opened 2023-04-02 00:43 UTC by steveluscher

test: remove test for priority fee that's ‘too high’
## Summary
My best guess here is that setting the priority fee high has no effect unless there's a bidder in the same block to outbid you. My solution here is to just remove the test.

## Test Plan
```
pnpm test:live-with-test-validator
```

2023-04-02 00:53 UTC, steveluscher commented
@taozhu-chicago, can I also get your eyes on this one? I think that setting the fee ‘too high’ no longer has any effect because there's no bidder in the same block to force you to pay that fee. Can you think of a way to rewrite this test in a way that exercises something, or should we just delete it as I've done here?

2023-04-02 04:32 UTC, taozhu-chicago commented
> @taozhu-chicago, can I also get your eyes on this one? I think that setting the fee ‘too high’ no longer has any effect because there's no bidder in the same block to force you to pay that fee. Can you think of a way to rewrite this test in a way that exercises something, or should we just delete it as I've done here?

The test being deleted seems to test a scenario that payer account should have enough balance to allow high prioritization fee, which sounds to me a valid test. Even there is no bidder to force, one is free to set prioritization fee to as high as payer account can pay for it -- i am thinking in a scenario that one *really* wants transaction to land in block without knowing if there are other bidders there (which should be a common case, is it?).

2023-04-02 04:33 UTC, taozhu-chicago requested changes
i think this test is valid, should not be removed.

2023-04-02 04:34 UTC, steveluscher commented
Well, with 1.16 the test doesn't pass. Do you have any ideas of what needs changing, @taozhu-chicago?

2023-04-02 04:35 UTC, steveluscher commented
> Even there is no bidder to force, one is free to set prioritization fee to as high as payer account can pay for it…

On 1.16, the test fails because this transaction _lands_. I'm guessing that means that the prioritization fee _isn't_ being charged, so the payer _isn't_ running out of funds to pay for it.

2023-04-02 04:48 UTC, taozhu-chicago commented
> Well, with 1.16 the test doesn't pass. Do you have any ideas of what needs changing, @taozhu-chicago?

I am not aware of any changes to how prioritization fee being charged - the test calculates p.fee correctly, as far as I can tell. I think the test is valid, if you agree too, then something must be wrong. We should fine out why. I am currently OOO. I'll be happy to look into it when I am back. Please tag me if you find more about it.

2023-04-11 22:39 UTC, steveluscher commented
This just started working again.

2023-04-11 22:39 UTC, closed without merging