feat(experimental): add `signatureNotifications` websocket method
solana-labs/solana-web3.js pull request #1649
Opened 2023-09-29 16:07 UTC by buffalojoec

2023-09-29 16:07 UTC, buffalojoec commented
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649?utm_source=stack-comment).

2023-09-29 16:07 UTC, buffalojoec commented
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649?utm_source=stack-comment).

2023-10-05 01:19 UTC, steveluscher approved these changes
[![closepuppy1](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lE1zD7Jpg6mWNv3djNKZ/a2673f59-4b21-4ad2-b6f0-8cd5e607f4b7/giphy-6.gif)](https://app.graphite.dev/macros/solana-labs)

2023-10-05 01:19 UTC, steveluscher requested changes
.

2023-10-05 11:16 UTC, buffalojoec commented on packages/rpc-core/src/rpc-subscriptions/signature-notifications.ts
> +    commitment?: Commitment;
Ahh nuts, must have hustled through this one. Adding!

2023-10-05 11:35 UTC, buffalojoec commented on packages/rpc-core/src/rpc-subscriptions/signature-notifications.ts
> +    commitment?: Commitment;
Added!

2023-10-06 09:31 UTC, merged