You can now post-process params at selected keypaths
solana-labs/solana-web3.js pull request #1966
Opened 2023-12-13 22:30 UTC by steveluscher

# Summary

The goal of the next PR is to default the commitment to `confirmed` for all methods that involve commitment. This overrides the server default of `finalized`, which we believe not to be practical for most use cases.

This PR adds infrastructure to allow you to inject node transformers that operate at key paths. See how this is used in the next PR.

# Test plan

```
cd packages/rpc-core/
pnpm test:unit:browser
pnpm test:unit:node
```

2023-12-13 22:30 UTC, steveluscher commented
Current dependencies on/for this PR:
* `master`
  * **PR #1966** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1966?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #1967** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1967?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1966?utm_source=stack-comment).

2023-12-13 23:24 UTC, buffalojoec approved these changes
![keyz](https://media.giphy.com/media/wKKnvfqzNOzo3Q3TwY/giphy.gif)

2023-12-13 23:24 UTC, buffalojoec commented on packages/rpc-core/src/__tests__/params-patcher-test.ts
> +        ${['foo', 1, 'bar']}  | ${{ baz: 1, foo: [2, { bar: 3 }, 4] }} | ${[3]}               | ${{ baz: 1, foo: [2, { bar: '🍕' }, 4] }}
Pizza tests!

2023-12-14 01:58 UTC, steveluscher commented
I changed this to make it recursive-ish. The tests are now _really_ subtle. Can you take another look at this and see that I got it right?

2023-12-14 10:36 UTC, lorisleiva requested changes
### Current Solution

I think there is a fundamental issue with this approach as **it reuses the existing recursive parameter transformer** whose purpose is to handle integer overflow.

The purpose of this PR is to eventually add another parameter transformer which will handle default commitment values. This one does not need to be recursive.

Moreover, this approach does not allow composing additional parameter transformers to the default ones. Composing transformers of any kind is an important aspect of building more complex RPC APIs and transports.

### Proposed Solution

What I suggest we do instead is **break up the current parameter transformers into two distinct transformers**:
- One recursive transformer that only handles integer overflow.
- One non-recursive transformer that accepts a `defaultCommitment` value and sets it on all relevant methods.

Then, we simply pipe the two together. That is, the transformed parameters of the former will be passed as arguments of the latter. That way, we end up with an array of parameters that have gone through all transformers without them needing to know about each other.

Additionally, we could accept an optional `extraParameterTransformer` (for lack of a better name) configuration that can be added at the end of the pipe should the end-user need to transform these parameters even further.

![CleanShot 2023-12-14 at 10 22 39@2x](https://github.com/solana-labs/solana-web3.js/assets/3642397/68b27445-3cc5-4990-93ec-c3a9bfb74c32)

2023-12-14 16:18 UTC, buffalojoec commented
Thanks @lorisleiva for the detailed overview.

What if we instead just offered a recursive and non-recursive transformer? You can choose to define `n` number of operations to perform on recursive node visits _or_ on particular key paths.

This way, one could stack `integerOverflow` and some other operations on recursive visits, while `defaultCommitment` could be combined with something like `defaultAccountEncoding` or `defaultTransactionDetails`.

This way, we avoid having to define a new config field for each type of transformer.

2023-12-14 16:45 UTC, lorisleiva commented
@buffalojoec I think we probably need to have a quick chat about this because I'm a bit confused.

I think it's much cleaner to have one way of composing transformers and then offer many transformers that each have one specific responsibility.

If someone happens to have another param transformer that needs to be recursive, then they can offer their own recursive transformer. I also think trying to offer a one-size-fits-all recursive solution is a bad idea. It's always very much case-by-case.

2023-12-14 16:51 UTC, buffalojoec commented
> @buffalojoec I think we probably need to have a quick chat about this because I'm a bit confused.
> 
> I think it's much cleaner to have one way of composing transformers and then offer many transformers that each have one specific responsibility.
> 
> If someone happens to have another param transformer that needs to be recursive, then they can offer their own recursive transformer. I also think trying to offer a one-size-fits-all recursive solution is a bad idea. It's always very much case-by-case.

Something sort of like this was what I was thinking, but I'm not sure how difficult it would be to implement `getRecursiveTransformer(..)` as defined.

```ts
type Config = Readonly<{
    getNodeTransformersForKeyPaths?: (methodName: string) => /* ?? */;
    getRecursiveTransformer?: (methodName: string, keyPath: (number | string)[], ...args) => void;
}>;
```

2023-12-14 16:58 UTC, lorisleiva commented
Noooooo. I really think neither `getNodeTransformersForKeyPaths` nor `getRecursiveTransformer` should be part of the configuration. They can be helper method to helper people build their own transformers if we want to, but they are implementation details. They are not the reason why we are adding them to the default RPC API.

2023-12-15 10:52 UTC, steveluscher commented
Abandoned in favor of #1977.

2023-12-15 10:52 UTC, closed without merging