refactor: polyfill importKey to satisfy instance of CryptoKey
solana-labs/solana-web3.js pull request #2349
Opened 2024-03-20 14:51 UTC by thepiwo

libraries like [jose](https://github.com/panva/jose) do check if keys are `instanceOf CryptoKey` (e.g. https://github.com/panva/jose/blob/main/src/runtime/browser/webcrypto.ts#L3)

Using `Object.setPrototypeOf` the created keys from the ED25519 polyfill can also satisfy this check.

2024-03-21 04:55 UTC, steveluscher requested changes
Oh wow. I didn't even think of that. Hero!

Can you hop over to `secrets-test.ts` and write tests for both of these?

2024-03-21 09:27 UTC, thepiwo commented
@steveluscher I'll do that!

2024-03-21 10:10 UTC, thepiwo commented
Actually, my fix doesn't seem to work in the test environment.

in `Unit Test (Node)` it works, but in `Unit Test (Browser)` I receive `ReferenceError: CryptoKey is not defined`, in my use-case in a different project I do use it successfully in a browser environment.

2024-03-21 16:57 UTC, steveluscher commented
Look in `setup-webcrypto` and glue the CryptoKey class to the global scope if it doesn't exist.

2024-03-22 10:05 UTC, thepiwo commented
@steveluscher thank you for the support, I tried that, but `prototype` isn't defined then, I didn't find a way to add this as well and currently don't have a good solution. Maybe "faking" the instance via `setPrototypeOf` in the first place isn't the best of ideas, even if it works in my use-case...

Would be open to try other suggestions if you have any.

I added this snippet in `setup-webcrypto.ts`: 
```
if (typeof globalThis.CryptoKey === 'undefined') {
     Object.defineProperty(globalThis, 'CryptoKey', {
        value: crypto.webcrypto.CryptoKey,
    });
}```

2024-04-16 08:00 UTC, closed without merging