Prevent the use of mismatching RPCs in factories that require a pair of RPCs (one-shot and subscriptions)
solana-labs/solana-web3.js pull request #2416
Opened 2024-04-02 21:43 UTC by steveluscher

# Summary

If you try to, say, get an airdrop but you use a devnet RPC to get the airdrop, and a testnet RPC to confirm the signature, you're going to have a bad time.

This PR attempts to enforce, via TypeScript, that you supply _matching_ RPCs wherever a pair is required.

Closes #2284.

# Test Plan

```
pnpm turbo test:typecheck
```

2024-04-02 21:44 UTC, steveluscher commented
* **#2416** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2416?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-02 22:40 UTC, buffalojoec reviewed
Nice. Overall this makes a lot of sense, especially considering airdrop is only for test clusters.

I want to at least call out that I bet the enforcement of lower-level clusters, and explicit barring of generic cluster, will definitely frustrate some people.

That being said, why have cluster-specific RPCs and APIs in the first place if we're not going to use them?! It's not unreasonable to require someone explicitly define a test-cluster transport/RPC in order to request test lamports with our API.

![do it](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbm9ybXhmeWI0anhpcHAzejd6ZWVlYjMyN29wZm04eWo1NjBqNXQ0diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o84sw9CmwYpAnRRni/giphy.gif)

2024-04-02 22:40 UTC, buffalojoec commented on packages/rpc-subscriptions/src/rpc-subscriptions-clusters.ts
> +        : RpcSubscriptions<TRpcMethods>;
```suggestion
export type RpcSubscriptionsFromCluster<
    TRpcMethods,
    TCluster extends ClusterUrl,
> = TCluster extends DevnetUrl
    ? RpcSubscriptionsDevnet<TRpcMethods>
    : TCluster extends TestnetUrl
      ? RpcSubscriptionsTestnet<TRpcMethods>
      : TCluster extends MainnetUrl
        ? RpcSubscriptionsMainnet<TRpcMethods>
        : RpcSubscriptions<TRpcMethods>;
```

2024-04-02 22:40 UTC, buffalojoec commented on packages/rpc/src/rpc-clusters.ts
> +        : Rpc<TRpcMethods>;
```suggestion
export type RpcFromCluster<
    TRpcMethods,
    TCluster extends ClusterUrl,
> = TCluster extends DevnetUrl
    ? RpcDevnet<TRpcMethods>
    : TCluster extends TestnetUrl
      ? RpcTestnet<TRpcMethods>
      : TCluster extends MainnetUrl
        ? RpcMainnet<TRpcMethods>
        : Rpc<TRpcMethods>;
```

2024-04-09 07:56 UTC, lorisleiva requested changes
IIRC, we agreed that the generic RPC should not fail in this case because it'll likely be used for local validators which do support airdrops.

2024-04-09 20:44 UTC, buffalojoec commented
> IIRC, we agreed that the generic RPC should not fail in this case because it'll likely be used for local validators which do support airdrops.

Bah, you're right. This made things much tricker! I've got a working implementation now for the type-checking, but the error messages are horrendous. Trying to iron that bit out, then I'll push another commit.

2024-04-10 06:54 UTC, lorisleiva approved these changes
This looks great!

2024-04-10 13:31 UTC, merged

2024-04-19 16:46 UTC, steveluscher commented
Nice. I intended to do this for all of the other places, other than airdrop, too. Search the code for `rpcSubscriptions: ` and you'll find the rest of them. Want to replicate what you've done here, there, @buffalojoec?

2024-04-19 17:13 UTC, buffalojoec commented
> Nice. I intended to do this for all of the other places, other than airdrop, too. Search the code for `rpcSubscriptions: ` and you'll find the rest of them. Want to replicate what you've done here, there, @buffalojoec?

#2534