[GraphQL]: Relay: Add support for `id` field in transactions
solana-labs/solana-web3.js pull request #2565
Opened 2024-04-25 14:09 UTC by tibi77

2024-04-26 15:22 UTC, tibi77 commented on packages/rpc-graphql/src/schema/transaction.ts
> +        id: Signature!
thanks; pushed

2024-04-26 15:33 UTC, buffalojoec requested changes
Cool, so this is the right first step, but our GraphQL client doesn't actually know how to populate that field. You'll need to hook that into the resolver here.

https://github.com/solana-labs/solana-web3.js/blob/35aed3c23bfb4d66585188a9633db3a9786a045b/packages/rpc-graphql/src/resolvers/transaction.ts#L105-L108

2024-04-26 15:33 UTC, buffalojoec commented on packages/rpc-graphql/src/__tests__/transaction-tests.ts
> +                        id: expect.any(String),
You can just put `signature` here.

2024-04-26 15:33 UTC, buffalojoec commented on packages/rpc-graphql/src/__tests__/transaction-tests.ts
> +                        id
tiny nit: ID fields are always at the top!

2024-04-27 09:22 UTC, tibi77 commented
> Cool, so this is the right first step, but our GraphQL client doesn't actually know how to populate that field. You'll need to hook that into the resolver here.
> 
> https://github.com/solana-labs/solana-web3.js/blob/35aed3c23bfb4d66585188a9633db3a9786a045b/packages/rpc-graphql/src/resolvers/transaction.ts#L105-L108

should i be adding the ID inside the buildTransactionLoaderArgSetFromResolveInfo as well? https://github.com/solana-labs/solana-web3.js/blob/35aed3c23bfb4d66585188a9633db3a9786a045b/packages/rpc-graphql/src/resolvers/resolve-info/transaction.ts#L79-L88

2024-04-28 14:20 UTC, buffalojoec commented
> should i be adding the ID inside the buildTransactionLoaderArgSetFromResolveInfo as well?

_Technically,_ that's not necessary for cache matching - since we're using another field for that - but to follow the expected Relay pattern I guess we should also include the ID.

2024-04-30 12:07 UTC, tibi77 commented
@buffalojoec I m trying to test locally the tests that are failing inside the pipeline, but i not getting same fails 

```
npm -v; pnpm -v
9.8.1
9.0.6
```
is it just because of the node versions? Or am i missing something else when i run the tests? 
```
node -v
v18.18.2
```

i do run 
```
```

2024-04-30 18:24 UTC, buffalojoec commented
> @buffalojoec I m trying to test locally the tests that are failing inside the pipeline, but i not getting same fails
> 
> ```
> npm -v; pnpm -v
> 9.8.1
> 9.0.6
> ```
> 
> is it just because of the node versions? Or am i missing something else when i run the tests?
> 
> ```
> node -v
> v18.18.2
> ```
> 
> i do run
> 
> ```
>  pnpm build --concurrency=100%
> ```
> 
> which seems to be the one that fails

I tend to get some flakiness from the main `pnpm turbo run build` command. But you definitely want to be using Node 20.

Try doing the following, and then running the tests only for the GraphQL library.

```
pnpm turbo clean
rm -rf node_modules
pnpm i
pnpm turbo compile:js compile:typedefs --force
cd packages/rpc-graphql
pnpm run test:unit:node
```

2024-05-07 20:04 UTC, buffalojoec commented
Hey @tibi77 I appreciate the contribution here, but I'm taking the Relay effort to a new branch `feature/graphql-relay`, and I've added the ID fields. Thanks!

Keep an eye on the issues if you want to keep hacking.

2024-05-07 20:04 UTC, closed without merging