refactor(experimental): change `UnixTimestamp` to `bigint`
solana-labs/solana-web3.js pull request #3121
Opened 2024-08-20 18:34 UTC by buffalojoec

2024-08-20 18:34 UTC, buffalojoec commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3121?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3122** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3122?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3121** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3121?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3120** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @buffalojoec and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-20 19:12 UTC, steveluscher requested changes
![Added via Giphy](https://media3.giphy.com/media/gx6xWk8ImrAiEjqsCP/giphy.gif?cid=c9487743j9prn27b77ggdj02q7rbtpuy5u0hgdmajjj6bip9&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-08-20 19:14 UTC, buffalojoec commented on packages/rpc-types/src/unix-timestamp.ts
> +export type UnixTimestamp = bigint & { readonly __brand: unique symbol };
Yeah this is true. Yuck.

2024-08-21 16:57 UTC, buffalojoec commented on packages/rpc-types/src/unix-timestamp.ts
> +export type UnixTimestamp = bigint & { readonly __brand: unique symbol };
Gross. Updated in next branch in the stack.

2024-08-22 11:47 UTC, mcintyre94 approved these changes

2024-08-27 19:50 UTC, buffalojoec commented
### Merge activity

* **Aug 27, 3:50 PM EDT**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3121).

2024-08-27 19:54 UTC, merged