Add `fromJson` and `toJson` options to HTTP transport
solana-labs/solana-web3.js pull request #3192
Opened 2024-09-02 11:32 UTC by lorisleiva

2024-09-02 11:33 UTC, lorisleiva commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3192?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3192** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3192?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3186** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3186?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3185** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3185?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3184** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3184?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lorisleiva and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-09 17:56 UTC, steveluscher requested changes

2024-09-10 16:17 UTC, steveluscher approved these changes
![Added via Giphy](https://media2.giphy.com/media/yNwov3KOhT74Ewg5b0/giphy.gif?cid=c94877436kardwabh2vwle3cv9o64gt0t3goooh3acgdr2o3&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-09-11 08:12 UTC, lorisleiva commented
### Merge activity

* **Sep 11, 4:12 AM EDT**: @lorisleiva started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3192).

2024-09-11 08:12 UTC, merged