Added programId field in TokenBalance type
solana-labs/solana-web3.js pull request #3592
Opened 2024-11-18 15:56 UTC by shivaji43

Tackles the issue (#3091)

2024-11-18 19:23 UTC, steveluscher requested changes
Adding this property to the TypeScript type is insufficient to vend it to the caller.

Look here:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L2329-L2334

To get your PRs in faster, make sure to test your changes, to write down in your PR description exactly what you did, and to paste in the results as proof that the code works.

2024-11-19 17:12 UTC, steveluscher requested changes
![giphy](https://github.com/user-attachments/assets/f2411035-3a3a-4bd1-8009-a8bab96d92db)

> To get your PRs in faster, make sure to test your changes, to write down in your PR description exactly what you did, and to paste in the results as proof that the code works.

Doing this will make it really easy for me to accept your PR with high confidence.

1. Run code quality scripts

        pnpm test:lint && pnpm test:typecheck && pnpm test:prettier

2. Build the code

        pnpm compile:js && pnpm compile:typedefs

3. Start a REPL

        pnpm node
        > const { Connection } = require('./lib/index.cjs.js');
        > const connection = new Connection('https://api.devnet.solana.com');

4. Do your testing. Use the `connection` instance to make a query, show that the `programId` field materializes on the response, and that there are no fatals. Paste all of your steps and results into the PR description

2024-11-19 17:12 UTC, steveluscher commented on src/connection.ts
> +  programId:optional(string()),
I can see that you haven't run any tests or build scripts, because this line of code isn't formatted.

2024-11-19 22:45 UTC, steveluscher requested changes
Almost!

The data structure you edited is called `TokenBalance`

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L1049-L1054

You can see it in use here:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L1085-L1088

And here:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L1116-L1119

Those properties are materialized here:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L2344-L2370

And here:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L2375-L2395

Look at all of the RPC calls that materialize `ConfirmedTransactionMetaResult` and `ParsedConfirmedTransactionMetaResult`.

You'll see that one such call is this one:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L2573C7-L2583

So find out where that is used:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/connection.ts#L5053-L5083

And there we have an actual RPC call you can make; `getTransaction()`. There are many others, but this is one. You could conceive of a transaction that you could get, then check `result.meta.postTokenBalances` to see if you got the new property!

Just make sure you actually use a transaction that involves SPL tokens, or that array will be empty and you won't learn anything.

2024-11-20 09:58 UTC, shivaji43 commented
![Screenshot 2024-11-20 152521](https://github.com/user-attachments/assets/ffc1377d-a31b-41b2-a150-126136f4195c)

I got it , I put one of my own transaction signature which involved actual token transfer  and i was able to the programId in the metadata array now.

2024-11-20 19:18 UTC, steveluscher commented
Beautiful. Thank you!

2024-11-20 19:34 UTC, merged

2024-11-21 01:59 UTC, shivaji43 commented
Thank you so much @steveluscher